/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_tam_muestras;

import AppPackage.AnimationClass;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barre
 */
public class sub_NoconoceN_cuali2 extends javax.swing.JFrame {
    int x,y;
     double Z ;
     double P;
     double q ;
     double d ;
    DefaultTableModel modelozzz = new DefaultTableModel() ;
  
    Fondopanel2 fondo11 = new Fondopanel2();

    /**
     * Creates new form sub_vantana_cuali2
     */
    public sub_NoconoceN_cuali2() {
        this.setResizable(false);
        this.setContentPane(fondo11);
       
        initComponents();
        modelozzz.addColumn("Z(alfa)^2");
        modelozzz.addColumn("p");
        modelozzz.addColumn("q");
        modelozzz.addColumn("d^2");
        modelozzz.addColumn("n(final)");
       tbldato1_cualiNO.setModel(modelozzz);
    }
    public void cargarDatos3(){
   
       txt_1_cualiNO1.setText(Double.toString(Z));
       txt_2_cualiNO2.setText(Double.toString(P));
       txt_3_cualiNO3.setText(Double.toString(q));
       txt_4_cualiNO4.setText(Double.toString(d));
       
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldato1_cualiNO = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txt_resulcualiNO1 = new javax.swing.JTextField();
        jLabel9_no_Z = new javax.swing.JLabel();
        jLabel10_no_p = new javax.swing.JLabel();
        txt_resulcualiNO2 = new javax.swing.JTextField();
        jLabel11_no_q = new javax.swing.JLabel();
        txt_resulcualiNO3 = new javax.swing.JTextField();
        jLabel12_no_d = new javax.swing.JLabel();
        txt_resulcualiNO4 = new javax.swing.JTextField();
        jLabel16_no_n = new javax.swing.JLabel();
        txt_resulcualiNO5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7_precalculo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_1_cualiNO1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_2_cualiNO2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_3_cualiNO3 = new javax.swing.JTextField();
        txt_4_cualiNO4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1_cuanti_conoceN = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23_Calcc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cualitativo - Se desconoce N");
        setMinimumSize(new java.awt.Dimension(1020, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1020, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbldato1_cualiNO = new javax.swing.JTable(){
            public boolean  isCellEditable(int rowIndex, int colIndex){
                return false;

            }
        };
        tbldato1_cualiNO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldato1_cualiNO.setGridColor(new java.awt.Color(51, 204, 0));
        jScrollPane1.setViewportView(tbldato1_cualiNO);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 470, 140));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-historial-de-pedidos-24.png"))); // NOI18N
        jLabel20.setText("HISTORIAL DE RESULTADOS : ");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 25));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-flecha-responder-32.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-eliminar-propiedad-26.png"))); // NOI18N
        jLabel9.setText("Eliminar Fila");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 100, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-eliminar-propiedad-26 (1).png"))); // NOI18N
        jLabel10.setText("Eliminar Todo");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 110, -1));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 690, 220));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_resulcualiNO1.setEditable(false);
        txt_resulcualiNO1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcualiNO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 71, -1));

        jLabel9_no_Z.setText("Z(alfa)^2:");
        jPanel6.add(jLabel9_no_Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 60, -1));

        jLabel10_no_p.setText("p:");
        jPanel6.add(jLabel10_no_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 21, -1));

        txt_resulcualiNO2.setEditable(false);
        txt_resulcualiNO2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcualiNO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 71, -1));

        jLabel11_no_q.setText("q:");
        jPanel6.add(jLabel11_no_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 20, -1));

        txt_resulcualiNO3.setEditable(false);
        txt_resulcualiNO3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcualiNO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 71, -1));

        jLabel12_no_d.setText("d^2 :");
        jPanel6.add(jLabel12_no_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 19));

        txt_resulcualiNO4.setEditable(false);
        txt_resulcualiNO4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcualiNO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 71, -1));

        jLabel16_no_n.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16_no_n.setText("Tamaño de muestra(n) :");
        jPanel6.add(jLabel16_no_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, -1));

        txt_resulcualiNO5.setEditable(false);
        txt_resulcualiNO5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_resulcualiNO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resulcualiNO5ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_resulcualiNO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 71, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-mayor-o-igual-2-64.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Mostrar Cálculos");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel7_precalculo.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7_precalculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-matemáticas-32.png"))); // NOI18N
        jLabel7_precalculo.setText("Pre Cálculos :");
        jPanel6.add(jLabel7_precalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 120, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 320, 310));

        jLabel3.setText("Nivel  de confianza Z(alfa) :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 130, 160, -1));

        txt_1_cualiNO1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_1_cualiNO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1_cualiNO1ActionPerformed(evt);
            }
        });
        txt_1_cualiNO1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_1_cualiNO1KeyTyped(evt);
            }
        });
        jPanel5.add(txt_1_cualiNO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 71, -1));

        jLabel5.setText("Probabilidad Positiva(p) :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 170, 150, -1));

        txt_2_cualiNO2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_2_cualiNO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_2_cualiNO2ActionPerformed(evt);
            }
        });
        txt_2_cualiNO2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_2_cualiNO2KeyTyped(evt);
            }
        });
        jPanel5.add(txt_2_cualiNO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 71, -1));

        jLabel6.setText("Probabilidad Negativa(q) :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 210, 150, 19));

        txt_3_cualiNO3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_3_cualiNO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_3_cualiNO3ActionPerformed(evt);
            }
        });
        txt_3_cualiNO3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_3_cualiNO3KeyTyped(evt);
            }
        });
        jPanel5.add(txt_3_cualiNO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 71, -1));

        txt_4_cualiNO4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_4_cualiNO4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_4_cualiNO4KeyTyped(evt);
            }
        });
        jPanel5.add(txt_4_cualiNO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 71, -1));

        jLabel15.setText("Máximo error de estimación (d) :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 250, 190, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calculate-64.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 90, 80));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel13.setText("TAMAÑO DE MUESTRA( SE DESCONOCE N)");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 380, 30));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-acercar-32.png"))); // NOI18N
        jLabel22.setText("INGRESAR DATOS");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 690, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/logo.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-menu-32.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tbl1_cuanti_conoceN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"99.7%", "3"},
                {"99%", "2.58"},
                {"98%", "2.33"},
                {"96%", "2.05"},
                {"95%", "1.96"},
                {"90%", "1.645"},
                {"80%", "1.28"},
                {"50%", "0.674"}
            },
            new String [] {
                "Nivel de Confianza", "Z(alfa)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl1_cuanti_conoceN);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 226, 147));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/DesconoceCuali.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 160, 70));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-help-64.png"))); // NOI18N
        jLabel17.setText("GUÍA : ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-hoja-de-datos-24.png"))); // NOI18N
        jLabel18.setText("Cuadro de Confianza :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-formula-fx-24.png"))); // NOI18N
        jLabel19.setText("Fórmula : ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel23_Calcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calculator-32 (1).png"))); // NOI18N
        jLabel23_Calcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23_CalccMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel23_Calcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 340, 640));

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-32 (1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-expand-arrow-32.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cualitativo");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 20));

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 690, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     public void refrescartabla(){
            double Z21 =Math.pow(Double.parseDouble(txt_1_cualiNO1.getText()),2) ;
            double p21 = Double.parseDouble(txt_2_cualiNO2.getText());
            double q21 = Double.parseDouble(txt_3_cualiNO3.getText());
            double d21 = Math.pow(Double.parseDouble(txt_4_cualiNO4.getText()),2);
            double n_final21 =  Math.ceil(((Z21*p21*q21)/d21));
            int n_sinpunto1 = (int)n_final21;
           
                Object xx[]=new Object[5];
                xx[0]=(double)Math.round(Z21 * 1000000d) / 1000000d;
                xx[1]=p21;
                xx[2]=q21;
                xx[3]=(double)Math.round(d21 * 1000000d) / 1000000d;
                xx[4]=n_sinpunto1;
                  
    modelozzz.addRow(xx);
  
    
    }
     
        public void vAlidadIngresoEnTabla21(){
            double Z212 =(double)Math.round(Math.pow(Double.parseDouble(txt_1_cualiNO1.getText()),2) * 1000000d) / 1000000d;
            double p212 = Double.parseDouble(txt_2_cualiNO2.getText());
            double q212 = Double.parseDouble(txt_3_cualiNO3.getText());
            double d212 = (double)Math.round(Math.pow(Double.parseDouble(txt_4_cualiNO4.getText()),2) * 1000000d) / 1000000d;
    for(int i=0 ; i<tbldato1_cualiNO.getRowCount();i++)
    {
        if(tbldato1_cualiNO.getValueAt(i,0).equals(Z212)&&
           tbldato1_cualiNO.getValueAt(i,1).equals(p212)&&
           tbldato1_cualiNO.getValueAt(i,2).equals(q212)&&
           tbldato1_cualiNO.getValueAt(i,3).equals(d212)
                
                
                
                )
        {
        JOptionPane.showMessageDialog(null, "Ya se realizó este cálculo");
        modelozzz.removeRow(i);
        }
    
        
    }
    refrescartabla();
    
   }
    private void txt_2_cualiNO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_2_cualiNO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_2_cualiNO2ActionPerformed

    private void txt_2_cualiNO2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2_cualiNO2KeyTyped
        // TODO add your handling code here:
        char validar33=evt.getKeyChar();
        if(Character.isLetter(validar33)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_2_cualiNO2KeyTyped

    private void txt_3_cualiNO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_3_cualiNO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_3_cualiNO3ActionPerformed

    private void txt_3_cualiNO3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_3_cualiNO3KeyTyped
        // TODO add your handling code here:
        char validar44=evt.getKeyChar();
        if(Character.isLetter(validar44)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_3_cualiNO3KeyTyped

    private void txt_1_cualiNO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1_cualiNO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1_cualiNO1ActionPerformed

    private void txt_1_cualiNO1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1_cualiNO1KeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_1_cualiNO1KeyTyped

    private void txt_4_cualiNO4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_4_cualiNO4KeyTyped
        // TODO add your handling code here:
        char validar4444=evt.getKeyChar();
        if(Character.isLetter(validar4444)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_4_cualiNO4KeyTyped

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
    jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
    jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    AnimationClass calculadoraa222  = new AnimationClass();
    calculadoraa222.jLabelXRight(-20, 20, 10, 5, jLabel23_Calcc);


 AnimationClass calculadoraa22  = new AnimationClass();
    calculadoraa22.jLabelXLeft(20, -20, 10, 5, jLabel23_Calcc);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    MENU men434 = new MENU();
    men434.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    if(txt_1_cualiNO1.getText().trim().isEmpty()||txt_2_cualiNO2.getText().trim().isEmpty() || txt_3_cualiNO3.getText().trim().isEmpty() || txt_4_cualiNO4.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null,"POR FAVOR, LLENAR TODOS LOS CAMPOS","Error",JOptionPane.WARNING_MESSAGE);

        }

        double Z21 = Math.pow(Double.parseDouble(txt_1_cualiNO1.getText()),2);
      
        double P21 = Double.parseDouble(txt_2_cualiNO2.getText());
        
        double Q21 =Double.parseDouble(txt_3_cualiNO3.getText());
      
        double D21 = Math.pow(Double.parseDouble(txt_4_cualiNO4.getText()),2);
        
        double n21 = ((Z21*P21*Q21)/(D21));
       

        txt_resulcualiNO1.setText(Double.toString((double)Math.round(Z21 * 1000000d) / 1000000d));
        txt_resulcualiNO2.setText(Double.toString(P21));
        txt_resulcualiNO3.setText(Double.toString(Q21));
        txt_resulcualiNO4.setText(Double.toString((double)Math.round(D21 * 1000000d) / 1000000d));
        txt_resulcualiNO5.setText(Double.toString((double)Math.round(n21 * 100000d) / 100000d));
        vAlidadIngresoEnTabla21();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    int dialog12344 = JOptionPane.YES_NO_OPTION;
        int result12344 = JOptionPane.showConfirmDialog(null,"¿Desea salir?","Exit",dialog12344);
        if(result12344==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    this.setState(MENU.ICONIFIED);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel23_CalccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23_CalccMouseClicked
        // TODO add your handling code here:
    try {
            Runtime rt1111 = Runtime.getRuntime();
            Process p112 = rt1111.exec("calc");
            p112.waitFor();
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_jLabel23_CalccMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
    AnimationClass precalculo_txt3  = new AnimationClass();
    precalculo_txt3.jLabelXLeft(300, 150, 10, 5, jLabel7_precalculo);
    AnimationClass precalculo_txt33  = new AnimationClass();
    precalculo_txt33.jLabelXRight(150, 300, 10, 5, jLabel7_precalculo);
    //
    
    //
   
    //
   
    //
    
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    AnimationClass z3  = new AnimationClass();
    z3.jTextFieldXLeft(300, 200, 10, 5, txt_resulcualiNO1);
    
    //
    AnimationClass P3  = new AnimationClass();
    P3.jTextFieldXLeft(300, 200, 10, 5, txt_resulcualiNO2);
    //
    AnimationClass Q3  = new AnimationClass();
    Q3.jTextFieldXLeft(300, 200, 10, 5, txt_resulcualiNO3);
    //
    AnimationClass D3  = new AnimationClass();
    D3.jTextFieldXLeft(300, 200, 10, 5, txt_resulcualiNO4);
    AnimationClass n3  = new AnimationClass();
    n3.jTextFieldXLeft(300, 200, 10, 5, txt_resulcualiNO5);

    
    
    
    
    
    
    ////////////////////////////////////////////////////////////////////////////////////////////////aqui va la parte de texto
    AnimationClass z_txt3  = new AnimationClass();
    z_txt3.jLabelXLeft(300, 120, 10, 5, jLabel9_no_Z);
    //
    AnimationClass P_txt3  = new AnimationClass();
    P_txt3.jLabelXLeft(300, 160, 10, 5, jLabel10_no_p);
    //
    AnimationClass Q_txt3  = new AnimationClass();
    Q_txt3.jLabelXLeft(300, 160, 10, 5, jLabel11_no_q);
    //
    AnimationClass D_txt3  = new AnimationClass();
    D_txt3.jLabelXLeft(300, 160, 10, 5, jLabel12_no_d);
    AnimationClass n_txt3  = new AnimationClass();
    n_txt3.jLabelXLeft(300, 50, 10, 5, jLabel16_no_n);
    
    
    /////////////////////////////////////////////////////////////////////////////////////////////aqui va la parte contraria de las varibles donde se ingresa datoS
   AnimationClass z33  = new AnimationClass();
    z33.jTextFieldXRight(200, 300, 10, 5, txt_resulcualiNO1);
    
    //
    AnimationClass P33  = new AnimationClass();
    P33.jTextFieldXRight(200, 300, 10, 5, txt_resulcualiNO2);
    //
    AnimationClass Q33  = new AnimationClass();
    Q33.jTextFieldXRight(200, 300, 10, 5, txt_resulcualiNO3);
    //
    AnimationClass D33  = new AnimationClass();
    D33.jTextFieldXRight(200, 300, 10, 5, txt_resulcualiNO4);
    AnimationClass n33  = new AnimationClass();
    n33.jTextFieldXRight(200, 300, 10, 5, txt_resulcualiNO5);
    ///////////////////////////////////////////////////////////////////////////////////////////// lo mismo pero parte texto
     AnimationClass z_txt33  = new AnimationClass();
    z_txt33.jLabelXRight(120, 300, 10, 5, jLabel9_no_Z);
    //
    AnimationClass P_txt33  = new AnimationClass();
    P_txt33.jLabelXRight(160, 300, 10, 5, jLabel10_no_p);
    //
    AnimationClass Q_txt33  = new AnimationClass();
    Q_txt33.jLabelXRight(160, 300, 10, 5, jLabel11_no_q);
    //
    AnimationClass D_txt33  = new AnimationClass();
    D_txt33.jLabelXRight(160, 300, 10, 5, jLabel12_no_d);
    AnimationClass n_txt33  = new AnimationClass();
    n_txt33.jLabelXRight(50, 300, 10, 5, jLabel16_no_n);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void txt_resulcualiNO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resulcualiNO5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resulcualiNO5ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:

        int fila = tbldato1_cualiNO.getSelectedRow();
        if(fila>=0){

            modelozzz.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar Fila");
        }

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        int fila = tbldato1_cualiNO.getRowCount();
        for(int i=fila-1;i>=0;i-- ){
            modelozzz.removeRow(i);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        // TODO add your handling code here:
     this.setLocation(this.getLocation().x+evt.getX() - x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
    x = evt.getX();
    y=evt.getY();
    }//GEN-LAST:event_jLabel11MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sub_NoconoceN_cuali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sub_NoconoceN_cuali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sub_NoconoceN_cuali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sub_NoconoceN_cuali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sub_NoconoceN_cuali2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10_no_p;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_no_q;
    private javax.swing.JLabel jLabel12_no_d;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16_no_n;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel23_Calcc;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7_precalculo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_no_Z;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl1_cuanti_conoceN;
    private javax.swing.JTable tbldato1_cualiNO;
    private javax.swing.JTextField txt_1_cualiNO1;
    private javax.swing.JTextField txt_2_cualiNO2;
    private javax.swing.JTextField txt_3_cualiNO3;
    private javax.swing.JTextField txt_4_cualiNO4;
    private javax.swing.JTextField txt_resulcualiNO1;
    private javax.swing.JTextField txt_resulcualiNO2;
    private javax.swing.JTextField txt_resulcualiNO3;
    private javax.swing.JTextField txt_resulcualiNO4;
    private javax.swing.JTextField txt_resulcualiNO5;
    // End of variables declaration//GEN-END:variables
class Fondopanel2 extends  JPanel{
private Image imagen;
@Override
 public void  paint(Graphics g){
    
     imagen = new ImageIcon(getClass().getResource("/IMAGENES/FONDO10.jpg")).getImage();
     g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
     setOpaque(false);
     super.paint(g);

}
}
}
