/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_tam_muestras;


import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author barre
 */
public class sub_conoceN_cuanti1 extends javax.swing.JFrame {
    double Z ;
     double N;
     double var ;
     double d ;
     int x,y;
    
    DefaultTableModel modelo = new DefaultTableModel() ;
   
    
   /**
     * Creates new form sub_conoceN_cuanti1
     */
    public sub_conoceN_cuanti1() {
        this.setResizable(false);
        
       
      
       initComponents();
        modelo.addColumn("Z(alfa)^2");
        modelo.addColumn("N");
        modelo.addColumn("σ^2");
        modelo.addColumn("d^2");
        modelo.addColumn("n(final)");
        
        tbldato1_cuanti.setModel(modelo);
        
        

    }
    
   public void cargarDatos1(){
   
       txt_1_cuantiN.setText(Double.toString(Z));
       txt_2_cuantiN.setText(Double.toString(N));
       txt_3_cuantiN.setText(Double.toString(var));
       txt_4_cuantiN.setText(Double.toString(d));
       
   
   }
   
    public void refrescartabla(){
    
    
            double Z11 =Math.pow(Double.parseDouble(txt_1_cuantiN.getText()),2) ;
            double N11 = Double.parseDouble(txt_2_cuantiN.getText());
            double var11 = Math.pow(Double.parseDouble(txt_3_cuantiN.getText()),2);
            double d11 = Math.pow(Double.parseDouble(txt_4_cuantiN.getText()),2);
            double n_final =  Math.ceil(N11*Z11*var11/(  ((N11-1)*d11)+(Z11*var11)));
            int n_sinpunto3 = (int)n_final;
                Object xx[]=new Object[5];
                xx[0]=(double)Math.round(Z11 * 1000000d) / 1000000d;
                xx[1]=N11;
                xx[2]=(double)Math.round(var11 * 1000000d) / 1000000d;;
                xx[3]=(double)Math.round(d11 * 1000000d) / 1000000d;;
                xx[4]=n_sinpunto3;
                  
    modelo.addRow(xx);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1_cuanti_conoceN = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10_calccc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_2_cuantiN = new javax.swing.JTextField();
        txt_3_cuantiN = new javax.swing.JTextField();
        txt_4_cuantiN = new javax.swing.JTextField();
        txt_1_cuantiN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldato1_cuanti = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7_precalculo = new javax.swing.JLabel();
        txt_resultados1 = new javax.swing.JTextField();
        jLabel9_Z = new javax.swing.JLabel();
        jLabel10_N = new javax.swing.JLabel();
        txt_resultados2 = new javax.swing.JTextField();
        txt_resultados3 = new javax.swing.JTextField();
        jLabel11_var = new javax.swing.JLabel();
        jLabel12_D = new javax.swing.JLabel();
        txt_resultados4 = new javax.swing.JTextField();
        jLabel14_n = new javax.swing.JLabel();
        txt_resultados5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuantitativo -Se conoce N");
        setMinimumSize(new java.awt.Dimension(1020, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1020, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/logo.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-help-64.png"))); // NOI18N
        jLabel16.setText("GUÍA : ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        tbl1_cuanti_conoceN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"99.7%", "3"},
                {"99%", "2.58"},
                {"98%", "2.33"},
                {"96%", "2.05"},
                {"95%", "1.96"},
                {"90%", "1.645"},
                {"80%", "1.28"},
                {"50%", "0.674"}
            },
            new String [] {
                "Nivel de Confianza", "Z(alfa)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl1_cuanti_conoceN);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 226, 150));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-hoja-de-datos-24.png"))); // NOI18N
        jLabel17.setText("Cuadro de Confianza :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-formula-fx-24.png"))); // NOI18N
        jLabel18.setText("Fórmula : ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cuantitativo_conoce_N.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 290, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-menu-32.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel10_calccc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calculator-32 (1).png"))); // NOI18N
        jLabel10_calccc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10_calcccMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10_calccc, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 340, 650));

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-expand-arrow-32.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 40, -1));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-32 (1).png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cuantitativo");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 20));

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 570, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 690, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-acercar-32.png"))); // NOI18N
        jLabel2.setText("INGRESAR DATOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel3.setText("Nivel  de confianza Z(alfa) :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        jLabel4.setText("Tamaño de Población(N) :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, -1));

        jLabel5.setText("Varianza( σ^2) :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, -1));

        jLabel6.setText("Máximo error de estimación (d) :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));

        txt_2_cuantiN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_2_cuantiN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_2_cuantiNKeyTyped(evt);
            }
        });
        jPanel1.add(txt_2_cuantiN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 71, -1));

        txt_3_cuantiN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_3_cuantiN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_3_cuantiNActionPerformed(evt);
            }
        });
        txt_3_cuantiN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_3_cuantiNKeyTyped(evt);
            }
        });
        jPanel1.add(txt_3_cuantiN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 71, -1));

        txt_4_cuantiN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_4_cuantiN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_4_cuantiNActionPerformed(evt);
            }
        });
        txt_4_cuantiN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_4_cuantiNKeyTyped(evt);
            }
        });
        jPanel1.add(txt_4_cuantiN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 71, -1));

        txt_1_cuantiN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_1_cuantiN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1_cuantiNActionPerformed(evt);
            }
        });
        txt_1_cuantiN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_1_cuantiNKeyTyped(evt);
            }
        });
        jPanel1.add(txt_1_cuantiN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 71, -1));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setText("TAMAÑO DE MUESTRA( SE CONOCE N)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 340, 30));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calculate-64.png"))); // NOI18N
        jLabel19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel19MouseMoved(evt);
            }
        });
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 70, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbldato1_cuanti = new javax.swing.JTable(){
            public boolean  isCellEditable(int rowIndex, int colIndex){
                return false;

            }
        };
        tbldato1_cuanti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldato1_cuanti.setGridColor(new java.awt.Color(51, 204, 0));
        jScrollPane1.setViewportView(tbldato1_cuanti);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 500, 130));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-historial-de-pedidos-24.png"))); // NOI18N
        jLabel13.setText("HISTORIAL DE RESULTADOS : ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 25));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-flecha-responder-32.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-eliminar-propiedad-26 (1).png"))); // NOI18N
        jLabel11.setText("Eliminar Todo");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 110, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-eliminar-propiedad-26.png"))); // NOI18N
        jLabel12.setText("Eliminar Fila ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 690, 220));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7_precalculo.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7_precalculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-matemáticas-32.png"))); // NOI18N
        jLabel7_precalculo.setText("Pre Cálculos :");
        jPanel5.add(jLabel7_precalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, -1));

        txt_resultados1.setEditable(false);
        txt_resultados1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel5.add(txt_resultados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 71, -1));

        jLabel9_Z.setText("Z(alfa)^2 :");
        jPanel5.add(jLabel9_Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 60, -1));

        jLabel10_N.setText("N :");
        jPanel5.add(jLabel10_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 22, -1));

        txt_resultados2.setEditable(false);
        txt_resultados2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel5.add(txt_resultados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 71, -1));

        txt_resultados3.setEditable(false);
        txt_resultados3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel5.add(txt_resultados3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 71, -1));

        jLabel11_var.setText("σ^2 :");
        jPanel5.add(jLabel11_var, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel12_D.setText("d^2 :");
        jPanel5.add(jLabel12_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 37, 19));

        txt_resultados4.setEditable(false);
        txt_resultados4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel5.add(txt_resultados4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 71, -1));

        jLabel14_n.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel14_n.setText("Tamaño de Muestra(n) :");
        jPanel5.add(jLabel14_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 140, -1));

        txt_resultados5.setEditable(false);
        txt_resultados5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_resultados5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultados5ActionPerformed(evt);
            }
        });
        jPanel5.add(txt_resultados5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 71, -1));

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Mostrar Cálculos");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-mayor-o-igual-2-64.png"))); // NOI18N
        jLabel23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel23MouseMoved(evt);
            }
        });
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, 90));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 690, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
   
    public void vAlidadIngresoEnTabla(){
    
            double Z111  =(double)Math.round(Math.pow(Double.parseDouble(txt_1_cuantiN.getText()),2) * 1000000d) / 1000000d;
            double N111 = Double.parseDouble(txt_2_cuantiN.getText());
            double var111 = (double)Math.round(Math.pow(Double.parseDouble(txt_3_cuantiN.getText()),2) * 1000000d) / 1000000d;
            double d111 = (double)Math.round(Math.pow(Double.parseDouble(txt_4_cuantiN.getText()),2) * 1000000d) / 1000000d;
    for(int i=0 ; i<tbldato1_cuanti.getRowCount();i++)
    {
        if(tbldato1_cuanti.getValueAt(i,0).equals(Z111)&&
           tbldato1_cuanti.getValueAt(i,1).equals(N111)&&
           tbldato1_cuanti.getValueAt(i,2).equals(var111)&&
           tbldato1_cuanti.getValueAt(i,3).equals(d111)
                
          
                
                
                
                )
        {
        JOptionPane.showMessageDialog(null, "Ya se realizó este cálculo");
        modelo.removeRow(i);
        }
    
        
    }
    refrescartabla();
    
   }
    private void txt_1_cuantiNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1_cuantiNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1_cuantiNActionPerformed

    private void txt_4_cuantiNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_4_cuantiNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_4_cuantiNActionPerformed

    private void txt_3_cuantiNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_3_cuantiNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_3_cuantiNActionPerformed

    private void txt_1_cuantiNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1_cuantiNKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
        
    }//GEN-LAST:event_txt_1_cuantiNKeyTyped

    private void txt_2_cuantiNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2_cuantiNKeyTyped
        // TODO add your handling code here:
        char validar1=evt.getKeyChar();
        if(Character.isLetter(validar1)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_2_cuantiNKeyTyped

    private void txt_3_cuantiNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_3_cuantiNKeyTyped
        // TODO add your handling code here:
        char validar3=evt.getKeyChar();
        if(Character.isLetter(validar3)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_3_cuantiNKeyTyped

    private void txt_4_cuantiNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_4_cuantiNKeyTyped
        // TODO add your handling code here:
        char validar4=evt.getKeyChar();
        if(Character.isLetter(validar4)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_4_cuantiNKeyTyped

    private void txt_resultados5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultados5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resultados5ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
if(txt_1_cuantiN.getText().trim().isEmpty()||txt_2_cuantiN.getText().trim().isEmpty() || txt_3_cuantiN.getText().trim().isEmpty() || txt_4_cuantiN.getText().trim().isEmpty()){
                
            JOptionPane.showMessageDialog(null,"POR FAVOR, LLENAR TODOS LOS CAMPOS","Error",JOptionPane.WARNING_MESSAGE);
            }
           
          
            double Z2 = Math.pow(Double.parseDouble(txt_1_cuantiN.getText()),2);
            double N2 = Double.parseDouble(txt_2_cuantiN.getText());
           double Var2=Math.pow(Double.parseDouble(txt_3_cuantiN.getText()),2);
           double D2 = Math.pow(Double.parseDouble(txt_4_cuantiN.getText()),2);
            
            double n1 = (N2*Z2*Var2)/(  ((N2-1)*D2)+(Z2*Var2));
             txt_resultados1.setText(Double.toString((double)Math.round(Z2 * 1000000d) / 1000000d));
            txt_resultados2.setText(Double.toString(N2));
            txt_resultados3.setText(Double.toString((double)Math.round(Var2 * 1000000d) / 1000000d));
            txt_resultados4.setText(Double.toString((double)Math.round(D2 * 1000000d) / 1000000d));
            txt_resultados5.setText(Double.toString((double)Math.round(n1 * 1000000d) / 1000000d));
              vAlidadIngresoEnTabla();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
int dialog123 = JOptionPane.YES_NO_OPTION;
        int result123 = JOptionPane.showConfirmDialog(null,"¿Desea salir?","Exit",dialog123);
        if(result123==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
this.setState(MENU.ICONIFIED);

    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
       // TODO add your handling code here:
       MENU men3 = new MENU(); 
       men3.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    //Aqui va la parte de los campos donde se ingresa los datos
    AnimationClass precalculo_txt  = new AnimationClass();
    precalculo_txt.jLabelXLeft(300, 160, 10, 5, jLabel7_precalculo);
    ////
   
    
     
    
   
    
    /////////////////////////////////////////////////////////////////////////////////////////
    AnimationClass z  = new AnimationClass();
    z.jTextFieldXLeft(300, 200, 10, 5, txt_resultados1);
    //
    AnimationClass N  = new AnimationClass();
    N.jTextFieldXLeft(300, 200, 10, 5, txt_resultados2);
    //
    AnimationClass varianza  = new AnimationClass();
    varianza.jTextFieldXLeft(300, 200, 10, 5, txt_resultados3);
    //
    AnimationClass d  = new AnimationClass();
    d.jTextFieldXLeft(300, 200, 10, 5, txt_resultados4);
    //
    AnimationClass n  = new AnimationClass();
    n.jTextFieldXLeft(300, 200, 10, 5, txt_resultados5);
    //aqui va la parte de texto
    ///////////////////////////////////////////////////////////////////////////////////////////////
    AnimationClass z_txt  = new AnimationClass();
    z_txt.jLabelXLeft(300, 130, 10, 5, jLabel9_Z);
    //
    AnimationClass N_txt  = new AnimationClass();
    N_txt.jLabelXLeft(300, 170, 10, 5, jLabel10_N);
    //
    AnimationClass var_txt  = new AnimationClass();
    var_txt.jLabelXLeft(300, 160, 10, 5, jLabel11_var);
    //
    AnimationClass D_txt  = new AnimationClass();
    D_txt.jLabelXLeft(300, 160, 10, 5, jLabel12_D);
    //
    AnimationClass n_txt  = new AnimationClass();
    n_txt.jLabelXLeft(300, 60, 10, 5, jLabel14_n);
    
    /////////////////////////////////////////////////////////////////////////////////////////////////aqui va la parte contraria de las varibles donde se ingresa datos
    AnimationClass z1  = new AnimationClass();
    z1.jTextFieldXRight(200, 300, 10, 5, txt_resultados1);
    AnimationClass N1  = new AnimationClass();
    N1.jTextFieldXRight(200,300, 10, 5, txt_resultados2);
    AnimationClass varianza1  = new AnimationClass();
    varianza1.jTextFieldXRight(200, 300, 10, 5, txt_resultados3);
    AnimationClass d1  = new AnimationClass();
    d1.jTextFieldXRight(200, 300, 10, 5, txt_resultados4);
    AnimationClass n1  = new AnimationClass();
    n1.jTextFieldXRight(200, 300, 10, 5, txt_resultados5);
    //////////////////////////////////////////////////////////////////////////////////////////////////// lo mismo pero parte texto
    AnimationClass z_txt1  = new AnimationClass();
    z_txt1.jLabelXRight(130, 300, 10, 5, jLabel9_Z);
    //
    AnimationClass N_txt1  = new AnimationClass();
    N_txt1.jLabelXRight(170, 300, 10, 5, jLabel10_N);
    //
    AnimationClass var_txt1  = new AnimationClass();
    var_txt1.jLabelXRight(160, 300, 10, 5, jLabel11_var);
    //
    AnimationClass D_txt1  = new AnimationClass();
    D_txt1.jLabelXRight(160, 300, 10, 5, jLabel12_D);
    //
    AnimationClass n_txt1  = new AnimationClass();
    n_txt1.jLabelXRight(60, 300, 10, 5, jLabel14_n);
    //
    AnimationClass precalculo_txt1  = new AnimationClass();
    precalculo_txt1.jLabelXRight(160, 300, 10, 5, jLabel7_precalculo);
    
    
    
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel19MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseMoved
        // TODO add your handling code here:
jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

    }//GEN-LAST:event_jLabel19MouseMoved

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel23MouseMoved

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
AnimationClass calculadoraaaa  = new AnimationClass();
    calculadoraaaa.jLabelXRight(-20, 20, 10, 5, jLabel10_calccc);


 AnimationClass calculadoraa11  = new AnimationClass();
    calculadoraa11.jLabelXLeft(20, -20, 10, 5, jLabel10_calccc);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10_calcccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10_calcccMouseClicked
        // TODO add your handling code here:
  
        try {
            Runtime rt111 = Runtime.getRuntime();
            Process p11 = rt111.exec("calc");
            p11.waitFor();
        }catch(Exception e){
        
        }

    }//GEN-LAST:event_jLabel10_calcccMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int fila = tbldato1_cuanti.getRowCount();
        for(int i=fila-1;i>=0;i-- ){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:

        int fila = tbldato1_cuanti.getSelectedRow();
        if(fila>=0){

            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar Fila");
        }

    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x+evt.getX() - x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jLabel10MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    x = evt.getX();
    y=evt.getY();
    }//GEN-LAST:event_jLabel10MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuanti1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuanti1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuanti1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuanti1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sub_conoceN_cuanti1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10_N;
    private javax.swing.JLabel jLabel10_calccc;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_var;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel12_D;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14_n;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7_precalculo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_Z;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl1_cuanti_conoceN;
    private javax.swing.JTable tbldato1_cuanti;
    private javax.swing.JTextField txt_1_cuantiN;
    private javax.swing.JTextField txt_2_cuantiN;
    private javax.swing.JTextField txt_3_cuantiN;
    private javax.swing.JTextField txt_4_cuantiN;
    private javax.swing.JTextField txt_resultados1;
    private javax.swing.JTextField txt_resultados2;
    private javax.swing.JTextField txt_resultados3;
    private javax.swing.JTextField txt_resultados4;
    private javax.swing.JTextField txt_resultados5;
    // End of variables declaration//GEN-END:variables

}
