/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_tam_muestras;

import AppPackage.AnimationClass;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barre
 */
public class sub_conoceN_cuali1 extends javax.swing.JFrame {
    int x,y;
    double Z33 ;
    double N33;
     double p33;
     double q33;
     double d33 ;
    
    DefaultTableModel modelo3 = new DefaultTableModel() ;
   
    
   Fondopanel23 fondo111 = new Fondopanel23();

    /**
     * Creates new form sub_ventana_cuali1
     */
    public sub_conoceN_cuali1() {
         this.setResizable(false);
        this.setContentPane(fondo111);
        initComponents();
        modelo3.addColumn("Z(alfa)^2");
        modelo3.addColumn("N");
        modelo3.addColumn("p");
        modelo3.addColumn("q");
        modelo3.addColumn("d^2");
        modelo3.addColumn("n(final)");
        tbldato1_cuali.setModel(modelo3);
    }
    
    public void cargarDatos4(){
   
       txt_1_cuali1.setText(Double.toString(Z33));
       txt_2_cuanli2.setText(Double.toString(N33));
       txt_3_cuali3.setText(Double.toString(p33));
       txt_4_cuali4.setText(Double.toString(q33));
       txt_5_cuali5.setText(Double.toString(d33));
       
       
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel22 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1_cuanti_conoceN = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26_calculadoraaa = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_1_cuali1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_2_cuanli2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_3_cuali3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_4_cuali4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_5_cuali5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldato1_cuali = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7_precalculo111 = new javax.swing.JLabel();
        jLabel9_Z_CUALi = new javax.swing.JLabel();
        txt_resulcuali1 = new javax.swing.JTextField();
        jLabel10_Ntxt = new javax.swing.JLabel();
        txt_resulcuali2 = new javax.swing.JTextField();
        jLabel11_Ptxt = new javax.swing.JLabel();
        txt_resulcuali3 = new javax.swing.JTextField();
        jLabel12_qTxt = new javax.swing.JLabel();
        txt_resulcuali4 = new javax.swing.JTextField();
        jLabel16_dTXt = new javax.swing.JLabel();
        txt_resulcuali5 = new javax.swing.JTextField();
        jLabel14_n_txt = new javax.swing.JLabel();
        txt_resulcuali7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cualitativo- Se conoce N");
        setMinimumSize(new java.awt.Dimension(1020, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1020, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl1_cuanti_conoceN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"99.7%", "3"},
                {"99%", "2.58"},
                {"98%", "2.33"},
                {"96%", "2.05"},
                {"95%", "1.96"},
                {"90%", "1.645"},
                {"80%", "1.28"},
                {"50%", "0.674"}
            },
            new String [] {
                "Nivel de Confianza", "Z(alfa)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl1_cuanti_conoceN);

        jPanel22.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 226, 147));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ConoceCuali.jpg"))); // NOI18N
        jPanel22.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 220, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/logo.png"))); // NOI18N
        jPanel22.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-menu-32.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-help-64.png"))); // NOI18N
        jLabel20.setText("GUÍA : ");
        jPanel22.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-hoja-de-datos-24.png"))); // NOI18N
        jLabel21.setText("Cuadro de Confianza :");
        jPanel22.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-formula-fx-24.png"))); // NOI18N
        jLabel22.setText("Fórmula : ");
        jPanel22.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel26_calculadoraaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calculator-32 (1).png"))); // NOI18N
        jLabel26_calculadoraaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26_calculadoraaaMouseClicked(evt);
            }
        });
        jPanel22.add(jLabel26_calculadoraaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 60, -1, -1));

        getContentPane().add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 340, 640));

        jPanel33.setBackground(new java.awt.Color(0, 153, 51));
        jPanel33.setForeground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cualitativo");
        jPanel33.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-expand-arrow-32.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel33.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-32 (1).png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel33.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel33.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 20));

        getContentPane().add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 700, 40));

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel55.setForeground(new java.awt.Color(255, 255, 255));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nivel  de confianza Z(alfa) :");
        jPanel55.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txt_1_cuali1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_1_cuali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1_cuali1ActionPerformed(evt);
            }
        });
        txt_1_cuali1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_1_cuali1KeyTyped(evt);
            }
        });
        jPanel55.add(txt_1_cuali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 71, -1));

        jLabel4.setText("Tamaño de Población(N) :");
        jPanel55.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, -1));

        txt_2_cuanli2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_2_cuanli2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_2_cuanli2KeyTyped(evt);
            }
        });
        jPanel55.add(txt_2_cuanli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 71, -1));

        jLabel5.setText("Probabilidad Positiva(p) :");
        jPanel55.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, -1));

        txt_3_cuali3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_3_cuali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_3_cuali3ActionPerformed(evt);
            }
        });
        txt_3_cuali3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_3_cuali3KeyTyped(evt);
            }
        });
        jPanel55.add(txt_3_cuali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 71, -1));

        jLabel6.setText("Probabilidad Negativa(q) :");
        jPanel55.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 19));

        txt_4_cuali4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_4_cuali4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_4_cuali4ActionPerformed(evt);
            }
        });
        txt_4_cuali4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_4_cuali4KeyTyped(evt);
            }
        });
        jPanel55.add(txt_4_cuali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 71, -1));

        jLabel15.setText("Máximo error de estimación (d) :");
        jPanel55.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, -1));

        txt_5_cuali5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_5_cuali5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_5_cuali5KeyTyped(evt);
            }
        });
        jPanel55.add(txt_5_cuali5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 71, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbldato1_cuali = new javax.swing.JTable(){
            public boolean  isCellEditable(int rowIndex, int colIndex){
                return false;

            }
        };
        tbldato1_cuali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldato1_cuali.setGridColor(new java.awt.Color(51, 204, 0));
        jScrollPane1.setViewportView(tbldato1_cuali);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 490, 130));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-historial-de-pedidos-24.png"))); // NOI18N
        jLabel13.setText("HISTORIAL DE RESULTADOS : ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 25));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-flecha-responder-32.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-eliminar-propiedad-26.png"))); // NOI18N
        jLabel9.setText("Eliminar Fila ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-eliminar-propiedad-26 (1).png"))); // NOI18N
        jLabel10.setText("Eliminar Todo");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 110, -1));

        jPanel55.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 700, 200));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7_precalculo111.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7_precalculo111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-matemáticas-32.png"))); // NOI18N
        jLabel7_precalculo111.setText("Pre Cálculos :");
        jPanel6.add(jLabel7_precalculo111, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 120, -1));

        jLabel9_Z_CUALi.setText("Z(alfa)^2:");
        jPanel6.add(jLabel9_Z_CUALi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 60, -1));

        txt_resulcuali1.setEditable(false);
        txt_resulcuali1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcuali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 71, 20));

        jLabel10_Ntxt.setText("N :");
        jPanel6.add(jLabel10_Ntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 37, -1));

        txt_resulcuali2.setEditable(false);
        txt_resulcuali2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcuali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 71, 20));

        jLabel11_Ptxt.setText("p:");
        jPanel6.add(jLabel11_Ptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 37, -1));

        txt_resulcuali3.setEditable(false);
        txt_resulcuali3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcuali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 71, 20));

        jLabel12_qTxt.setText("q :");
        jPanel6.add(jLabel12_qTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 22, 19));

        txt_resulcuali4.setEditable(false);
        txt_resulcuali4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel6.add(txt_resulcuali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 71, 20));

        jLabel16_dTXt.setText("d^2 :");
        jPanel6.add(jLabel16_dTXt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txt_resulcuali5.setEditable(false);
        txt_resulcuali5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_resulcuali5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resulcuali5ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_resulcuali5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 71, 20));

        jLabel14_n_txt.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel14_n_txt.setText("Tamaño de Muestra(n) :");
        jPanel6.add(jLabel14_n_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 140, -1));

        txt_resulcuali7.setEditable(false);
        txt_resulcuali7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        txt_resulcuali7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resulcuali7ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_resulcuali7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 71, 20));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-mayor-o-igual-2-64.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 90, 80));

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Mostrar Cálculos");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jPanel55.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 290, 340));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calculate-64.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel55.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, 90));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-acercar-32.png"))); // NOI18N
        jLabel2.setText("INGRESAR DATOS");
        jPanel55.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel17.setText("TAMAÑO DE MUESTRA( SE CONOCE N)");
        jPanel55.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 340, 30));

        getContentPane().add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 700, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       public void refrescartabla(){
           
           double Z221 =Math.pow(Double.parseDouble(txt_1_cuali1.getText()),2) ;
            double N221 = Double.parseDouble(txt_2_cuanli2.getText());
            double p221 = Double.parseDouble(txt_3_cuali3.getText());
            double q221 = Double.parseDouble(txt_4_cuali4.getText());
            double d221 =Math.pow(Double.parseDouble(txt_5_cuali5.getText()),2) ;
            double n_final211 = Math.ceil(((N221*Z221*p221*q221)/(  ((N221-1)*d221)+(Z221*p221*q221))));
            int n_sinpunto = (int)n_final211;
                   
           
                Object xxx[]=new Object[6];
                xxx[0]=(double)Math.round(Z221 * 1000000d) / 1000000d;
                xxx[1]=N221;
                xxx[2]=p221;
                xxx[3]=q221;
                xxx[4]=(double)Math.round(d221 * 1000000d) / 1000000d;
                xxx[5]=n_sinpunto;
                  
    modelo3.addRow(xxx);
   
    }
       public void vAlidadIngresoEnTabla21222(){
            double Z2122 =(double)Math.round(Math.pow(Double.parseDouble(txt_1_cuali1.getText()),2) * 1000000d) / 1000000d;
            double N2122 = Double.parseDouble(txt_2_cuanli2.getText());
            double p2122 = Double.parseDouble(txt_3_cuali3.getText());
            double q2122 = Double.parseDouble(txt_4_cuali4.getText());
            double d2122 = (double)Math.round(Math.pow(Double.parseDouble(txt_5_cuali5.getText()),2) * 1000000d) / 1000000d;
    for(int i=0 ; i<tbldato1_cuali.getRowCount();i++)
    {
        if(tbldato1_cuali.getValueAt(i,0).equals(Z2122) &&
           tbldato1_cuali.getValueAt(i,1).equals(N2122)&&
           tbldato1_cuali.getValueAt(i,2).equals(p2122)&&
           tbldato1_cuali.getValueAt(i,3).equals(q2122)&&
           tbldato1_cuali.getValueAt(i,4).equals(d2122)
                
          
              
           )
                     
     {
        JOptionPane.showMessageDialog(null, "Ya se realizó este cálculo");
        modelo3.removeRow(i);
        }
    
        
    }
    refrescartabla();
    
   }
    private void txt_2_cuanli2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2_cuanli2KeyTyped
        // TODO add your handling code here:
        char validar112=evt.getKeyChar();
        if(Character.isLetter(validar112)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_2_cuanli2KeyTyped

    private void txt_3_cuali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_3_cuali3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_3_cuali3ActionPerformed

    private void txt_3_cuali3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_3_cuali3KeyTyped
        // TODO add your handling code here:
        char validar33=evt.getKeyChar();
        if(Character.isLetter(validar33)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_3_cuali3KeyTyped

    private void txt_4_cuali4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_4_cuali4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_4_cuali4ActionPerformed

    private void txt_4_cuali4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_4_cuali4KeyTyped
        // TODO add your handling code here:
        char validar44=evt.getKeyChar();
        if(Character.isLetter(validar44)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_4_cuali4KeyTyped

    private void txt_1_cuali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1_cuali1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1_cuali1ActionPerformed

    private void txt_1_cuali1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1_cuali1KeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }

    }//GEN-LAST:event_txt_1_cuali1KeyTyped

    private void txt_5_cuali5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5_cuali5KeyTyped
        // TODO add your handling code here:
        char validar443=evt.getKeyChar();
        if(Character.isLetter(validar443)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txt_5_cuali5KeyTyped

    private void txt_resulcuali5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resulcuali5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resulcuali5ActionPerformed

    private void txt_resulcuali7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resulcuali7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resulcuali7ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
       MENU men44 = new MENU();
       men44.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    if(txt_1_cuali1.getText().trim().isEmpty()||txt_2_cuanli2.getText().trim().isEmpty() || txt_3_cuali3.getText().trim().isEmpty() || txt_4_cuali4.getText().trim().isEmpty()|| txt_5_cuali5.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null,"POR FAVOR, LLENAR TODOS LOS CAMPOS","Error",JOptionPane.WARNING_MESSAGE);

        }

        double Z2 = Math.pow(Double.parseDouble(txt_1_cuali1.getText()),2);
        double N2 = Double.parseDouble(txt_2_cuanli2.getText());
        double P2 =Double.parseDouble(txt_3_cuali3.getText());
        double Q2 = Double.parseDouble(txt_4_cuali4.getText());
        double D2 = Math.pow(Double.parseDouble(txt_5_cuali5.getText()),2);
        double n2 = ((N2*Z2*P2*Q2)/(  ((N2-1)*D2)+(Z2*P2*Q2)));
        txt_resulcuali1.setText(Double.toString((double)Math.round(Z2 * 1000000d) / 1000000d));
        txt_resulcuali2.setText(Double.toString(N2));
        txt_resulcuali3.setText(Double.toString(P2));
        txt_resulcuali4.setText(Double.toString(Q2));
        txt_resulcuali5.setText(Double.toString((double)Math.round(D2 * 1000000d) / 1000000d));
        txt_resulcuali7.setText(Double.toString((double)Math.round(n2 * 100000d) / 100000d));
        
        vAlidadIngresoEnTabla21222();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
    jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
   jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    AnimationClass calculadoraaaaa  = new AnimationClass();
    calculadoraaaaa.jLabelXRight(-30, 30, 10, 5, jLabel26_calculadoraaa);


 AnimationClass calculadoraa111  = new AnimationClass();
    calculadoraa111.jLabelXLeft(30, -30, 10, 5, jLabel26_calculadoraaa);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel26_calculadoraaaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26_calculadoraaaMouseClicked
        // TODO add your handling code here:
     try {
            Runtime rt1111 = Runtime.getRuntime();
            Process p111 = rt1111.exec("calc");
            p111.waitFor();
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_jLabel26_calculadoraaaMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
    int dialog1231 = JOptionPane.YES_NO_OPTION;
        int result1234 = JOptionPane.showConfirmDialog(null,"¿Desea salir?","Exit",dialog1231);
        if(result1234==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    this.setState(MENU.ICONIFIED);

    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    AnimationClass precalculo_txt2  = new AnimationClass();
    precalculo_txt2.jLabelXLeft(290, 140, 10, 5, jLabel7_precalculo111);
    AnimationClass precalculo_txt22  = new AnimationClass();
    precalculo_txt22.jLabelXRight(140, 290, 10, 5, jLabel7_precalculo111);
    //
    
    //
   
    //
   
    //
    
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    AnimationClass z2  = new AnimationClass();
    z2.jTextFieldXLeft(290, 170, 10, 5, txt_resulcuali1);
    //
    AnimationClass N2  = new AnimationClass();
    N2.jTextFieldXLeft(290, 170, 10, 5, txt_resulcuali2);
    //
    AnimationClass P2  = new AnimationClass();
    P2.jTextFieldXLeft(290, 170, 10, 5, txt_resulcuali3);
    //
    AnimationClass Q2  = new AnimationClass();
    Q2.jTextFieldXLeft(290, 170, 10, 5, txt_resulcuali4);
    //
    AnimationClass D2  = new AnimationClass();
    D2.jTextFieldXLeft(290, 170, 10, 5, txt_resulcuali5);
    AnimationClass n2  = new AnimationClass();
    n2.jTextFieldXLeft(290, 170, 10, 5, txt_resulcuali7);

    
    
    
    
    
    
    ////////////////////////////////////////////////////////////////////////////////////////////////aqui va la parte de texto
    AnimationClass z_txt2  = new AnimationClass();
    z_txt2.jLabelXLeft(290, 90, 10, 5, jLabel9_Z_CUALi);
    //
    AnimationClass N_txt2  = new AnimationClass();
    N_txt2.jLabelXLeft(290, 130, 10, 5, jLabel10_Ntxt);
    //
    AnimationClass P_txt2  = new AnimationClass();
    P_txt2.jLabelXLeft(290, 130, 10, 5, jLabel11_Ptxt);
    //
    AnimationClass Q_txt2  = new AnimationClass();
    Q_txt2.jLabelXLeft(290, 130, 10, 5, jLabel12_qTxt);
    //
    AnimationClass D_txt2  = new AnimationClass();
    D_txt2.jLabelXLeft(290, 120, 10, 5, jLabel16_dTXt);
    AnimationClass n_txt2  = new AnimationClass();
    n_txt2.jLabelXLeft(290, 20, 10, 5, jLabel14_n_txt);
    
    
    /////////////////////////////////////////////////////////////////////////////////////////////aqui va la parte contraria de las varibles donde se ingresa datoS
   AnimationClass z22  = new AnimationClass();
    z22.jTextFieldXRight(170, 290, 10, 5, txt_resulcuali1);
    //
    AnimationClass N22  = new AnimationClass();
    N22.jTextFieldXRight(170, 290, 10, 5, txt_resulcuali2);
    //
    AnimationClass P22  = new AnimationClass();
    P22.jTextFieldXRight(170, 290, 10, 5, txt_resulcuali3);
    //
    AnimationClass Q22  = new AnimationClass();
    Q22.jTextFieldXRight(170, 290, 10, 5, txt_resulcuali4);
    //
    AnimationClass D22  = new AnimationClass();
    D22.jTextFieldXRight(170, 290, 10, 5, txt_resulcuali5);
    AnimationClass n22  = new AnimationClass();
    n22.jTextFieldXRight(170, 290, 10, 5, txt_resulcuali7);
    ///////////////////////////////////////////////////////////////////////////////////////////// lo mismo pero parte texto
      AnimationClass z_txt22  = new AnimationClass();
    z_txt22.jLabelXRight(90, 290, 10, 5, jLabel9_Z_CUALi);
    //
    AnimationClass N_txt22  = new AnimationClass();
    N_txt22.jLabelXRight(130, 290, 10, 5, jLabel10_Ntxt);
    //
    AnimationClass P_txt22  = new AnimationClass();
    P_txt22.jLabelXRight(130, 290, 10, 5, jLabel11_Ptxt);
    //
    AnimationClass Q_txt22 = new AnimationClass();
    Q_txt22.jLabelXRight(130, 290, 10, 5, jLabel12_qTxt);
    //
    AnimationClass D_txt22  = new AnimationClass();
    D_txt22.jLabelXRight(120, 290, 10, 5, jLabel16_dTXt);
    AnimationClass n_txt22  = new AnimationClass();
    n_txt22.jLabelXRight(20, 290, 10, 5, jLabel14_n_txt);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    int fila = tbldato1_cuali.getRowCount();
    for(int i=fila-1;i>=0;i-- ){
    modelo3.removeRow(i);
    }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
        int fila = tbldato1_cuali.getSelectedRow();
    if(fila>=0){
    
    modelo3.removeRow(fila);
    }else{
            JOptionPane.showMessageDialog(null,"Seleccionar Fila");
            }
        
        
        
    
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x+evt.getX() - x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLabel11MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuali1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuali1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuali1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sub_conoceN_cuali1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sub_conoceN_cuali1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10_Ntxt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_Ptxt;
    private javax.swing.JLabel jLabel12_qTxt;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14_n_txt;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16_dTXt;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26_calculadoraaa;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7_precalculo111;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_Z_CUALi;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl1_cuanti_conoceN;
    private javax.swing.JTable tbldato1_cuali;
    private javax.swing.JTextField txt_1_cuali1;
    private javax.swing.JTextField txt_2_cuanli2;
    private javax.swing.JTextField txt_3_cuali3;
    private javax.swing.JTextField txt_4_cuali4;
    private javax.swing.JTextField txt_5_cuali5;
    private javax.swing.JTextField txt_resulcuali1;
    private javax.swing.JTextField txt_resulcuali2;
    private javax.swing.JTextField txt_resulcuali3;
    private javax.swing.JTextField txt_resulcuali4;
    private javax.swing.JTextField txt_resulcuali5;
    private javax.swing.JTextField txt_resulcuali7;
    // End of variables declaration//GEN-END:variables
class Fondopanel23 extends  JPanel{
private Image imagen;
@Override
 public void  paint(Graphics g){
    
     imagen = new ImageIcon(getClass().getResource("/IMAGENES/FONDO10.jpg")).getImage();
     g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
     setOpaque(false);
     super.paint(g);

}
}
}
